README.md
I added the schedule, the topics, the groups and references.
=> #1 Update Course Information

fav_songs_group_test.txt
=>  #3 test song

fav_songs_group_test.txt
=> #3 favorite song

fav_songs_group_test.txt
=> #3 test_branch

fav_songs_group_Zari_Gabriela.txt
=> #3 Misguided Ghosts letra

fav_songs_group_Espinoza_Carlos.txt
=> #3 passionfruitCarlos

fav_songs_group_Espinoza_Carlos.txt
=> #3 CANCION_FAVORITA

group_4_ass_1_2024.txt
=> #19 database_Lidia

group_4_ass_1_2024.txt
I added my database information
=> #19 My information

group_4_ass_1_2024.txt
=> Group 4 ass 1 2024

Lecture1/Assignment_1/group_1_ass_1_2024.txt
Add the list of winners for best picture
=> #24 Oscar winners 2023

Lecture1/Assignment_1/group_6_ass_1_2024.txt
I wrote the database I would like to work with and also added my reason.
=> #19 The database I would like to work with

group_1_ass_1_2024.txt
=> #24  citizen insecurity

Lecture1/Assignment_1/group_6_ass_1_2024.txt
I wrote the database I would like to work with and also added my reason.
=>     The database I would like to work with

Lecture1/Assignment_1/group_1_ass_1_2024_01.txt
Add data about citizen insecurity
=> #30 citizen insecurity

Lecture1/Assignment_1/group_5_ass_1_2024.txt
Datos de ganadores de los Golden Globes entre 2010-2020
=> #19 Golden Globes

Lecture1/Assignment_1/group_5_ass_1_2024.txt
Datos sobre la cantidad de pacientes con covid-19 en el Perú
=> #19 Pacientes Covid

group_2_ass_1_2024.txt
I added the information from the database
=> #19 2 data base

Lecture1/Assignment_1/group_3_ass_1_2024.txt
I just added information about the database of my interest
=> #19 Database I'm interested in

Lecture1/Assignment_1/group_3_ass_1_2024.txt
=> #19 Database_Katherine

Lecture1/Assignment_1/group_6_ass_1_2024.txt
I add the information required
=> #19 Assignment 1 Alejandra

Lecture1/Assignment_1/group_1_ass_1_2024.txt, Lecture1/Assignment_1/group_1_ass_1_2024_01.txt
I added data about crime rates in Lima, Peru.
=> Group 1 ass 1 2024 alice

Lecture1/Assignment_1/group_1_ass_1_2024.txt
=> #30 Email added

Lecture1/Assignment_1/group_6_ass_1_2024.txt
The database I'd like to work with
=> #19 Claudia's database

Lecture1/Assignment_1/group_6_ass_1_2024.txt
Fundamental database to comprehend crimes by Epstein
=> #19 Epstein's crimes

Lecture1/Assignment_1/group_1_ass_1_2024.txt
Info about people killed during Dina Boluarte's goverment
=> #19 PCM DATA PROTESTS

Lecture1/Assignment_1/group_1_ass_1_2024.txt
add data about prisions in Lima
=> #19 prisions

Lecture1/Assignment_1/group_1_ass_1_2024.txt
=> #19 Minedu

Lecture2/Assignment_2/group_6_ass_2_2024.ipynb
Here is my part of the homework: 5 solved exercises (number 6 of Tuple section and the first four of Lists section)
=> #60 Abraham´s resolution

Lecture2/Assignment_2/group_5_ass_2_2024.ipynb
=> #60 Pregunta 1.2

Lecture2/Assignment_2/group_5_ass_2_2024.ipynb
=> #60 Pregunta 1.3

Lecture2/Assignment_2/group_5_ass_2_2024.ipynb
=> #60 PREGUNTA 1.4

Lecture2/Assignment_2/group_5_ass_2_2024.ipynb
=> #60 Pregunta 5

Lecture2/Assignment_2/group_5_ass_2_2024.ipynb
=> #60 Ejercicio 6

Lecture_2/Assignment_2/.ipynb_checkpoints/group_4_ass_2_2024-checkpoint.ipynb, Lecture_2/Assignment_2/group_4_ass_2_2024.ipynb
Create everything again and this is the first attempt to see if the changes appear on the notebook
=> #60 First test

Lecture_2/Assignment_2/.ipynb_checkpoints/group_3_ass_2_2024-checkpoint.ipynb, Lecture_2/Assignment_2/group_3_ass_2_2024.ipynb
Done second section_List (1 to 8)
=> #60_KatherineFlores

Lecture_2/Assignment_2/.ipynb_checkpoints/group_3_ass_2_2024-checkpoint.ipynb, Lecture_2/Assignment_2/group_3_ass_2_2024.ipynb
I've done the "Strings" part, exercises from 1 to 6.
=> #60 Assignment_2_MarcoCardoso

Lecture2/Assignment_2/.ipynb_checkpoints/group_6_ass_2_2024-checkpoint.ipynb, Lecture2/Assignment_2/group_6_ass_2_2024.ipynb
I add my part of the assignment
=> #60 Alejandra

Lecture_2/Assignment_2/group_4_ass_2_2024 - editada.ipynb, Lecture_2/Assignment_2/group_4_ass_2_2024.ipynb
=> #60 other time

Lecture_1/Assignment_1/group_4_ass_correction_1_2024.txt
This is my correction of the assignemt 1
=> #19 Part 1

Lecture_1/Assignment_1/group_4_ass_correction_1_2024.txt
I join the database of my tesis
=> #19 join my database

Lecture_1/Assignment_1/group_4_ass_correction_1_2024.txt
I added the database from my tesis
=> #19 I added my database

Lecture_1/Assignment_1/group_4_ass_correction_1_2024.txt
we have finished the correction of the assigment 1
=> Group 4 corretion ass 1 2024

Lecture2/Assignment_2/.ipynb_checkpoints/group_6_ass_2_2024-checkpoint.ipynb, Lecture2/Assignment_2/group_6_ass_2_2024.ipynb
=> #60 Italo's results

Lecture2/Assignment_2/group_5_ass_2_2024.ipynb
Yo hice el ejercicio 1,2,3 y 4.
=> #60 Ejercicio de listas

Lecture2/Assignment_2/group_5_ass_2_2024.ipynb
=> #60 Ejercicios listos

Lecture2/Assignment_2/.ipynb_checkpoints/group_6_ass_2_2024-checkpoint.ipynb
Return of the folder ".ipynb_checkpoints"
=> #60 Re-add of the checkpoint folder

Lecture2/Assignment_2/group_5_ass_2_2024.ipynb
Realice los ejercicios del 1-6
=> #60 Ejercicio de string

Lecture_2/Assignment_2/.ipynb_checkpoints/group_1_ass_2_2024-checkpoint.ipynb, Lecture_2/Assignment_2/group_1_ass_2_2024.ipynb
=> #60 Tuple with titles

Lecture_1/Assignment_1/group_6_ass_1_2024_correction.txt
All about my preferences of databases are ready.
=> #19 Abraham´s part

Lecture_1/Assignment_1/group_6_ass_1_2024_correction.txt
I added information about the dataset I'd like to study
=> #19 Claudia's fixes

Lecture_1/Assignment_1/group_6_ass_1_2024_correction.txt
=> #19 Alejandra´s part

Lecture_1/Assignment_1/group_6_ass_1_2024_correction.txt
Important database to know and to have an important opinion
=> #19 Epstein's abuses

Lecture_1/Assignment_1/group_6_ass_1_2024_correction.txt
=> Group 6 ass 1 2024 correction

Lecture_3/Assignment_3/.ipynb_checkpoints/group_6_ass_3_2024-checkpoint.ipynb, Lecture_3/Assignment_3/group_6_ass_3_2024.ipynb
Here are the first three steps ready.
=> #113 Abraham´s part

Lecture_3/Assignment_3/.ipynb_checkpoints/group_3_ass_3_2024-checkpoint.ipynb, Lecture_3/Assignment_3/group_3_ass_3_2024.ipynb
I've done the 3rd exercise and corrected a syntax error in exercise 2.
=> #113 Exercise 3

Lecture_3/Assignment_3/.ipynb_checkpoints/group_3_ass_3_2024-checkpoint.ipynb, Lecture_3/Assignment_3/group_3_ass_3_2024.ipynb
=> #113 4,5,6 Katherine

Lecture_3/Assignment_3/.ipynb_checkpoints/group_6_ass_3_2024-checkpoint.ipynb, Lecture_3/Assignment_3/group_6_ass_3_2024.ipynb
=> #113 3,4 and 5 Panda's problems

Lecture_3/Assignment_3/.ipynb_checkpoints/group_6_ass_3_2024-checkpoint.ipynb, Lecture_3/Assignment_3/group_6_ass_3_2024.ipynb
=> #113 Alejandra´s part

Lecture_1/Assignment_1/group_3_ass_1_2024.txt
I've chosen Most Followed on Instagram because I think it's important in my job.
=> #19 Assignment 1 - Marco Cardoso

Lecture_1/Assignment_1/group_3_ass_1_2024.txt
I would like to know the situation of the probabilities of the Phenomenon in the country
=> #19 database Katherine Flores

Lecture_1/Assignment_1/group_3_ass_1_2024.txt
I've added my database about the perception on the current political system in Peru because it's relevant to my career.
=> #19 Assignment 1 Gabriela Zari Database

Lecture_3/Assignment_3/.ipynb_checkpoints/group_1_ass_3_2024-checkpoint.ipynb, Lecture_3/Assignment_3/group_1_ass_3_2024.ipynb
I created the file for the group to work
=> #113 file created

Lecture_3/Assignment_3/group_6_ass_3_2024.ipynb
=> #113 Claudia's exercises

Lecture_4/Assignment_4/.ipynb_checkpoints/group_6_ass_4_2024-checkpoint.ipynb, Lecture_4/Assignment_4/group_6_ass_4_2024.ipynb
=> #134 Abraham´s part

Lecture_4/Assignment_4/group_3_ass_4_2024.ipynb
=> #134 Assignment 4

Lecture_4/Assignment_4/.ipynb_checkpoints/group_4_ass_4_2024-checkpoint.ipynb, Lecture_4/Assignment_4/group_4_ass_4_2024.ipynb
=> #134 FINISH

Lecture_4/Assignment_4/.ipynb_checkpoints/group_1_ass_4_2024-checkpoint.ipynb, Lecture_4/Assignment_4/group_1_ass_4_2024.ipynb
=> #134  branch group 4

Lecture_5/Assignment_5/group_3_ass_5_2024.ipynb
I've uploaded the JN with the task.
=> #169 Assignment 5

Lecture_5/Assignment_5/group_5_ass_5_2024.ipynb
Avance todo hasta la seleccion del departamento
=> #169 IMPORTACION DE URL

Lecture_5/Assignment_5/group_4_ass_5_2024.ipynb
hi team, this is the grupal brach. pls Jorge start the project (part 1)
=> #169 grupal branch

Lecture_5/Assignment_5/.ipynb_checkpoints/group_3_ass_5_2024-checkpoint.ipynb, Lecture_5/Assignment_5/group_3_ass_5_2024.ipynb
I explained the steps carried out in the first part
=> #169 Done Katherine

Lecture_5/Assignment_5/group_4_ass_5_2024.ipynb
=> #169 I added my part

Lecture_5/Assignment_5/.ipynb_checkpoints/group_6_ass_5_2024-checkpoint.ipynb, Lecture_5/Assignment_5/group_6_ass_5_2024.ipynb
Here is the process with the libraries and drivers ready without the final table.
=> #169 Progress_Only_Clicks

Lecture_5/Assignment_5/.ipynb_checkpoints/group_6_ass_5_2024-checkpoint.ipynb, Lecture_5/Assignment_5/group_6_ass_5_2024.ipynb
I added my part of the exercise
=> #169 Alejandra´s part

Lecture_4/Assignment_4/.ipynb_checkpoints/group_1_ass_4_2024-checkpoint.ipynb, Lecture_4/Assignment_4/group_1_ass_4_2024.ipynb
=> #134  final exercise 3

Lecture_5/Assignment_5/.ipynb_checkpoints/group_1_ass_5_2024-checkpoint.ipynb, Lecture_5/Assignment_5/group_1_ass_5_2024.ipynb
=> #169 new file 5

Lecture_5/Assignment_5/.ipynb_checkpoints/group_1_ass_5_2024-checkpoint.ipynb, Lecture_5/Assignment_5/group_1_ass_5_2024.ipynb, Lecture_5/lecture_5.ipynb
=> #169 Run excercise
